services:
  poll:
    build: .
    container_name: poll
    env_file:
      - .env
    depends_on:
      - influxdb
    devices:
      - /dev/ttyUSB0
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./influxdb:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: always
    ports:
      - 8086:8086

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    volumes:
      - ./grafana:/var/lib/grafana:rw
    depends_on:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SERVER_ROOT_URL=https://boiler.blip2.net/
    restart: always
    ports:
      - 3000:3000

  grafana-ntfy:
    image: academo/grafana-ntfy:latest
    hostname: grafana-ntfy
    expose:
      - 8080
    command: "-ntfy-url=https://ntfy.blip2.net/lmws"
