{
 "title": "Boiler Data",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Pressure and Temperature",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"temp1\"\r\n  )"
    },
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"pressure\"\r\n  )"
    }
   ]
  },
  {
   "title": "Boiler Pressure",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"pressure\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"lockout\"\r\n  )"
    }
   ]
  },
  {
   "title": "Shell Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"temp1\"\r\n  )\r\n  |> last()"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"running\"\r\n  )"
    }
   ]
  },
  {
   "type": "state-timeline",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"feedpump\"\r\n  )"
    }
   ]
  }
 ]
}