{
 "title": "Boiler Run Stats",
 "time": { "from": "2023-12-26T00:00:00.000Z", "to": "2024-01-01T23:59:59.000Z" },
 "panels": [
  {
   "title": "Pressure and Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"pressure\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    },
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"temp1\"\r\n  )\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "Pressure Change",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "Bar / 5min" } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"pressure\"\r\n  )\r\n  |> derivative(unit: 5m)\r\n  |> aggregateWindow(every: 5m, fn: mean)"
    }
   ]
  },
  {
   "title": "Boiler Total Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hrs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"running\"\r\n  )\r\n  |> elapsed(unit: 1s)\r\n  |> map(fn: (r) => ({ r with runtime: float(v: r.elapsed)/3660.0 }))\r\n  |> filter(fn: (r) => r[\"_value\"] == true)\r\n  |> sum(column:\"runtime\")"
    }
   ]
  },
  {
   "title": "Run Hours Per Day",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 11, "x": 3, "y": 15 },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"running\"\r\n  )\r\n  |> elapsed(unit: 1s)\r\n  |> map(fn: (r) => ({ r with runtime: float(v: r.elapsed)/3600.0 }))\r\n  |> filter(fn: (r) => r[\"_value\"] == true)\r\n  |> aggregateWindow(every: 1d, fn: sum, column:\"runtime\", timeSrc: \"_start\")\r\n  |> yield(name: \"sum\")"
    },
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"feedpump\"\r\n  )\r\n  |> elapsed(unit: 1s)\r\n  |> map(fn: (r) => ({ r with pumptime: float(v: r.elapsed)/3600.0 }))\r\n  |> filter(fn: (r) => r[\"_value\"] == true)\r\n  |> aggregateWindow(every: 1d, fn: sum, column:\"pumptime\", timeSrc: \"_start\")\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Starts Per Day",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 10, "x": 14, "y": 15 },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\r\nfrom(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"running\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _level: if r._value then \"1\" else \"0\" }))\r\n  |> monitor.stateChanges(toLevel: \"1\")\r\n  |> map(fn: (r) => ({ r with burnerstarts: float(v: r._level) }))\r\n  |> aggregateWindow(every: 24h, fn: sum, column:\"burnerstarts\", timeSrc: \"_start\")\r\n  |> yield(name: \"sum\")"
    },
    {
     "query": "import \"influxdata/influxdb/monitor\"\r\nfrom(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"feedpump\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _level: if r._value then \"1\" else \"0\" }))\r\n  |> monitor.stateChanges(toLevel: \"1\")\r\n  |> map(fn: (r) => ({ r with pumpstarts: float(v: r._level) }))\r\n  |> aggregateWindow(every: 1d, fn: sum, column:\"pumpstarts\", timeSrc: \"_start\")\r\n  |> yield(name: \"sum\")"
    }
   ]
  },
  {
   "title": "Feed Pump Total Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "hrs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"feedpump\"\r\n  )\r\n  |> elapsed(unit: 1s)\r\n  |> map(fn: (r) => ({ r with runtime: float(v: r.elapsed)/3660.0 }))\r\n  |> filter(fn: (r) => r[\"_value\"] == true)\r\n  |> sum(column:\"runtime\")"
    }
   ]
  },
  {
   "title": "Burner Starts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\r\nfrom(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"running\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _level: if r._value then \"1\" else \"0\" }))\r\n  |> monitor.stateChanges(toLevel: \"1\")\r\n  |> map(fn: (r) => ({ r with burnerstarts: float(v: r._level) }))\r\n  |> sum(column:\"burnerstarts\")"
    }
   ]
  },
  {
   "title": "Feed Pump Starts",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "import \"influxdata/influxdb/monitor\"\r\nfrom(bucket: \"data\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._field == \"feedpump\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _level: if r._value then \"1\" else \"0\" }))\r\n  |> monitor.stateChanges(toLevel: \"1\")\r\n  |> map(fn: (r) => ({ r with feedpumpstarts: float(v: r._level) }))\r\n  |> sum(column:\"feedpumpstarts\")"
    }
   ]
  }
 ]
}